In [140]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [141]:
df = pd.read_csv('movies_metadata.csv')

In [142]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [143]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [145]:
df.shape

(45466, 24)

In [146]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [147]:
df.duplicated().sum()

np.int64(13)

In [148]:
df = df.drop_duplicates().reset_index(drop=True) 
# reset index mtlb index fie se 0,1,2 se start hoga

In [149]:
df.duplicated().sum()

np.int64(0)

In [150]:
df = df[['title','overview','genres','tagline','vote_average','vote_count','popularity','belongs_to_collection']]

In [151]:
df

,title,overview,genres,tagline,vote_average,vote_count,popularity,belongs_to_collection
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,5415.0,21.946943,"{'id': 10194, 'name': 'Toy Story Collection', ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,NaN
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,"{'id': 119050, 'name': 'Grumpy Old Men Collect..."
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,34.0,3.859495,NaN
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,"{'id': 96871, 'name': 'Father of the Bride Col..."
...,...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,1.0,0.072051,NaN
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,3.0,0.178241,NaN
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,6.0,0.903007,NaN
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.0,0.003503,NaN
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.0,0.163015,NaN

In [152]:
# we need to find similarites for such kind of projects and for that we need to use algo like cosine similarity

In [153]:
df.isnull().sum()

title                        6
overview                   954
genres                       0
tagline                  25045
vote_average                 6
vote_count                   6
popularity                   5
belongs_to_collection    40959
dtype: int64

In [154]:
df = df.dropna(subset=['title'])

In [155]:
# overview pe jo null values hai unn pr hum empty space chhod skte hai

In [156]:
df['overview'] = df['overview'].fillna('')

In [157]:
df.iloc[0]['genres']
import ast

In [158]:
df['genres'] = df['genres'].apply(lambda x:" ".join([i['name']for i in ast.literal_eval(x)]))

In [159]:
# ast import converts the python looking string to the actual python list/dict

In [160]:
df.head()

,title,overview,genres,tagline,vote_average,vote_count,popularity,belongs_to_collection
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,5415.0,21.946943,"{'id': 10194, 'name': 'Toy Story Collection', ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,NaN
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,"{'id': 119050, 'name': 'Grumpy Old Men Collect..."
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495,NaN
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,"{'id': 96871, 'name': 'Father of the Bride Col..."

In [161]:
df['tagline'] = df['tagline'].fillna('')

In [162]:
df.isnull().sum()

title                        0
overview                     0
genres                       0
tagline                      0
vote_average                 0
vote_count                   0
popularity                   0
belongs_to_collection    40957
dtype: int64

In [163]:
# we will combine all 3 like overview, tagline , geners : why cos then sbko ek hst numbers me 
# convert kr sku

In [164]:
df['tags'] = df['overview']+" "+df['genres']+ " " + df['tagline']

In [165]:
df.head()

,title,overview,genres,tagline,vote_average,vote_count,popularity,belongs_to_collection,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,5415.0,21.946943,"{'id': 10194, 'name': 'Toy Story Collection', ...","Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,NaN,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495,NaN,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,"{'id': 96871, 'name': 'Father of the Bride Col...",Just when George Banks has recovered from his ...

In [166]:
# now converts these tags into numbers

In [167]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [168]:
# removing the puncuations and limitation(word to root word)

In [169]:
import nltk
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer
import re

In [170]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tinij\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tinij\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [171]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [172]:
def preprocess_text(text):
    # handling missing/non string values
    if not isinstance(text,str):
        return ""
    # lowercase
    # remove puncuation
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]','',text)
    # tokenization and remove sstopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]
    # lemmatization 
    words = [lemmatizer.lemmatize(word) for word in words]
    # list to string 

    return " ".join(words)

In [173]:
df['tags'] = df['tags'].apply(preprocess_text)

In [174]:
df.head()

,title,overview,genres,tagline,vote_average,vote_count,popularity,belongs_to_collection,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,5415.0,21.946943,"{'id': 10194, 'name': 'Toy Story Collection', ...",led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,NaN,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495,NaN,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,"{'id': 96871, 'name': 'Father of the Bride Col...",george bank recovered daughter wedding receive...

In [175]:
# converting each sentences into vector

In [176]:
df = df.reset_index(drop=True)
# koi indexmis missing then remve it and reindex all

In [177]:
indices = pd.Series(df.index,index=df['title'])

indices = indices[~indices.index.duplicated(keep='first')]
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Caged Heat 3000                45440
Subdue                         45442
Century of Birthing            45443
Satan Triumphant               45445
Queerama                       45446
Length: 42277, dtype: int64

In [178]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [179]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')
# dict soize 500k

In [180]:
# conver to vector if all then it would be 2D = matrix
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [181]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548416 stored elements and shape (45447, 50000)>

In [182]:
# Cosine Similarity

In [183]:
from sklearn.metrics.pairwise import cosine_similarity

In [184]:
def recommend(title, n=10):
    if title not in indices:
        return ['Movie not found']

    idx = indices[title]

    print("Index:", idx)
    print("Movie:", df.iloc[idx]['title'])
    print("Tags:", df.iloc[idx]['tags'])
    print("Number of TF-IDF words:", tfidf_matrix[idx].nnz)

    sim_score = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    print("Maximum similarity:", sim_score.max())
    print("Non-zero similarities:", np.count_nonzero(sim_score))

    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_idx]

In [185]:
recommend('Avatar')

Index: 14547
Movie: Avatar
Tags: nd century paraplegic marine dispatched moon pandora unique mission becomes torn following order protecting alien civilization action adventure fantasy science fiction enter world pandora
Number of TF-IDF words: 30
Maximum similarity: 1.0000000000000002
Non-zero similarities: 17838

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
43431    Moontrap: Target Earth
14119      The Three Musketeers
28403    France société anonyme
43983       Nightmare City 2035
20372                    Désiré
28633      Stand by Me Doraemon
7472       Frank Herbert's Dune
Name: title, dtype: object

In [190]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))